language: bash

os: linux

before_script:
        #****sudo apt-get install tree -y
        #setup environment for testing GRADLER
        source src/gradle_setup.bash
        install_java
        install_gradle

script:
        #run tests
        source tests/test_gradle_setup.bats

notifications:
        email:
                on_success: change
                on_failure: change
