language: bash

os: linux

before_script:
        sudo apt-get install tree -y
script:
        #run tests
        source test_emulator_accel.sh 

notifications:
        email:
                on_success: change
                on_failure: change
