language: bash

os: linux
before_script:
        #install dependencies
        bash src/run_installs.sh
script:
        #run tests
        bash run_tests.sh

notifications:
        email:
                on_success: never
