language: bash

os: linux

before_script:
        #build the necessary environment for android development
        source src/setup_environment.sh
script:
        #run tests
        echo hello
        #source run_tests.sh

notifications:
        email:
                on_success: change
                on_failure: change
