language: bash

os: linux

before_script:
        #build the necessary environment for android development
        #bash src/setup_environment.sh
script:
        #run tests
        bash run_tests.sh

notifications:
        email:
                on_success: never
