language: bash

os: linux
before_script:
        #install dependencies
        ./src/run_installs.sh
script:
        #run tests
        ./run_tests.sh

notifications:
        email:
                on_success: never
