source set_env_vars.bash

set_var_gradle
set_var_marker_tools
set_var_android_sdk_root

export_emulator
export_platform_tools

source src/bash/emulator_manager_lib.bash
set_var_android_avd_home
set_var_avd_logs
