version: 2.1
jobs:
  build: 
    machine: 
        image: ubuntu-2004:202010-01 #using ubuntu 20 image
    steps:
      - checkout
      - run: source src/gradle_setup.bash && install_java && install_gradle && ./bats/bin/bats tests/test_gradle_setup.bats -T
