version: 2.1
executors:
        ubuntu20:
                machine:
                        image: ubuntu-2004:202010-01 

jobs:
        php_play:
                executor: ubuntu20
                steps:
                        - run:
                                command: |
                                        sudo apt-get update
                                        sudo apt-get install nginx -y

        php_test:
                executor: ubuntu20
                steps:
                     - checkout
                     - run:
                             command: |
                                     #update apt repositories
                                     sudo apt-get update
                                     #install php7.4, sqlite3 and php-sqlite driver
                                     sudo apt-get install php7.4 -y
                                     sudo apt-get install php7.4-sqlite3 -y
                                     sudo apt-get install sqlite3 -y
                                     #install composer required extensions to be able to run codecept
                                     sudo apt-get install php7.4-curl php7.4-mbstring php7.4-xml php7.4-zip -y
                                     #run unit tests with codecept
                                     php7.4 codecept.phar run unit
                                     
                                     #install webserver
                                     #sudo apt-get install nginx -y
                                     #create ams dir on webserver
                                     sudo mkdir /var/www/html/ams
                                     sudo chmod 775 /var/www/html/ams
                                     sudo cp -R src/* /var/www/html/ams
                                     #run acceptance tests with codecept
                                     php7.4 codecept.phar run acceptance SubmitCest
        gradler_php:
                executor: ubuntu20
                steps:
                     - checkout
                     - run:
                             command: |
                                     #update apt repositories
                                     sudo apt-get update
                                     #install php7.4
                                     sudo apt-get install php7.4 -y
     
                                     #install composer required extensions to be able to run codecept
                                     sudo apt-get install php7.4-curl php7.4-mbstring php7.4-xml php7.4-zip -y
                                    
                                     #set gradle environment
                                     source src/bash/gradle_setup.bash
                                     source set_env_vars.bash

                                     set_var_gradle

                                     install_java
                                     mkdir -p $GRADLE
                                     install_gradle $GRADLE

                                     ##run gradle bash tests
                                     ./bats/bin/bats tests/bash/test_gradle_setup.bats -T
                                     
                                     #install android sdk
                                     source src/bash/android_cmdline_lib.bash
                                     
                                     set_var_marker_tools
                                     set_var_android_sdk_root
                                     get_commandline_tools

                                     #run Gradler unit tests with codecept
                                     #php7.4 codecept.phar run unit

                                     #install android emulator dependencies
                                     #source src/bash/android_cmdline_lib.bash
                                     #set_var_android_sdk_root
                                     #get_commandline_tools
                                     #export tools
                                     export_emulator
                                     export_platform_tools

                                     #run test on emulator operations
                                     source src/bash/emulator_manager_lib.bash
                                     set_var_android_avd_home
                                     #install_emulator_image "28" "google_apis" "x86"
                                     install_emulator_image "29" "default" "x86_64"

                                     export TERM=xterm #solves tput error which might be caused by "pretty format" requested below
                                     #-----COMMENTED FOR FAST TEST EXECUTION
                                     #./bats/bin/bats tests/bash/test_android_environment.bats -T || ( echo "Android environment tests failed!" && exit 1 )
                                     #./bats/bin/bats tests/bash/test_avd_management.bats -T || ( echo "AVD management tests failed!" && exit 1 )
                                     #--------
                                     #TODO tests for online avd
                                     #./bats/bin/bats tests/bash/test_online_emulator.bats -T || ( echo "Online emulator tests failed!" && exit 1)
                                     #**********
                                     #testing starting of avd
                                     set_var_avd_logs
                                     mkdir -p $AVD_LOGS
                                     create_avd "0" "29" "default" "x86_64"
                                     #create_avd "2" "28" "google_apis" "x86"
                                     #create_avd "4" "28" "google_apis" "x86"
                                     #create_avd "100" "28" "google_apis" "x86"

                                     start_avd "0"
                                     echo "Device 1"
                                     adb -s emulator-5554 shell service list
                                     #wait_for_services "0"
                                     sleep 350
                                     adb -s emulator-5554 shell service list
                                     #start_avd "2"
                                     #start_avd "4"
                                     #run Gradler install
                                     php7.4 codecept.phar run unit GradlerTest:testPlay
                                     #check installed third party packages on devices[Want to see if gradle installed on all devices]
                                     adb -s emulator-5554 shell 'pm list packages -f -3'
                                     exit 0
                                     echo "Device 2"
                                     adb -s emulator-5556 shell 'pm list packages -f'
                                     echo "Device 3"
                                     adb -s emulator-5558 shell 'pm list packages -f'
        
        emulator:
                executor: ubuntu20
                steps:
                        - checkout
                        - run:
                                command: |
                                        sudo apt-get update
                                        #run emulator management tests
                                        source set_env_vars.bash
                                        #install android emulator dependencies
                                        source src/bash/android_cmdline_lib.bash
                                        set_var_android_sdk_root
                                        get_commandline_tools
                                        #export tools
                                        export_emulator
                                        export_platform_tools

                                        #run test on emulator operations
                                        source src/bash/emulator_manager_lib.bash
                                        set_var_android_avd_home
                                        install_emulator_image "28" "default" "x86_64"
                                        export TERM=xterm #solves tput error which might be caused by "pretty format" requested below
                                        ./bats/bin/bats tests/bash/test_android_environment.bats -T || ( echo "Android environment tests failed!" && exit 1 )
                                        ./bats/bin/bats tests/bash/test_avd_management.bats -T || ( echo "AVD management tests failed!" && exit 1 )
                                        #./bats/bin/bats tests/bash/test_online_emulator.bats -T || ( echo "Online emulator tests failed!" && exit 1)
                                        #**********
                                        #testing starting of avd
                                        set_var_avd_logs
                                        mkdir -p $AVD_LOGS
                                        create_avd "0" "28" "default" "x86_64"
                                        create_avd "2" "28" "default" "x86_64"
                                        create_avd "4" "28" "default" "x86_64"
                                        create_avd "100" "28" "default" "x86_64"

                                        start_avd "0"
                                        start_avd "2"
                                        start_avd "4"
                                        start_avd "100"

                                        adb devices
workflows:
        "Basic Workflow":
                jobs:
                        - gradler_php:
                                filters:
                                        branches:
                                                only:
                                                        - gradler
                        - php_test:
                                filters:
                                        branches:
                                                only:
                                                        - main
