version: 2.1
executors:
        ubuntu20:
                machine:
                        image: ubuntu-2004:202010-01 

jobs:
        php_play:
                executor: ubuntu20
                steps:
                        - run:
                                command: |
                                        sudo apt-get update
                                        sudo apt-get install nginx -y
                                        systemctl status nginx



        php_test:
                executor: ubuntu20
                steps:
                     - checkout
                     - run:
                             command: |
                                     #update apt repositories
                                     sudo apt-get update
                                     #install php7.4, sqlite3 and php-sqlite driver
                                     sudo apt-get install php7.4 -y
                                     sudo apt-get install php7.4-sqlite3 -y
                                     sudo apt-get install sqlite3 -y
                                     #install composer required extensions to be able to run codecept
                                     sudo apt-get install php7.4-curl php7.4-mbstring php7.4-xml php7.4-zip -y
                                     #run unit tests with codecept
                                     php7.4 codecept.phar run unit
                                     #run acceptance tests with codecept
                                     php7.4 codecept.phar run acceptance SubmitCest

workflows:
        "Basic Workflow":
                jobs:
                        - php_play:
                                filters:
                                        branches:
                                                only:
                                                        - main
