version: 2.1
executors:
        ubuntu20:
                machine:
                        image: ubuntu-2004:202010-01 

jobs:
        php_unit_test:
                executor: ubuntu20
                steps:
                     - checkout
                     - run:
                             command: |
                                     #install php7.4, sqlite3 and php-sqlite driver
                                     sudo apt-get install php7.4
                                     sudo apt-get install php7.4-sqlite3
                                     sudo apt-get install sqlite3
                                     #run unit tests with codecept
                                     php7.4 codeception.phar run unit

workflows:
        "Basic Workflow":
                jobs:
                        - php_unit_test:
                                filters:
                                        branches:
                                                only:
                                                        - main
