version: 2.1
executors:
        ubuntu20:
                machine:
                        image: ubuntu-2004:202010-01 

jobs:
        php_unit_test:
                executor: ubuntu20
                steps:
                     - checkout
                     - run:
                             ls .

workflows:
        "Basic Workflow":
                jobs:
                        - php_unit_test:
                                filters:
                                        branches:
                                                only:
                                                        - main
